/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Frank' at '20.12.16 10:32' with Gradle 2.13
 *
 * @author Frank, @date 20.12.16 10:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
