import org.junit.Test;

import junit.framework.TestCase;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Frank' at '20.12.16 10:32' with Gradle 2.13
 *
 * @author Frank, @date 20.12.16 10:32
 */
public class LibraryTest extends TestCase {
	Library classUnderTest;
	
	@Override
	public void setUp() {
		classUnderTest = new Library();
	}
	
    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testSomeLibraryMethod2() {
        assertFalse("someLibraryMethod2 should return 'true'", classUnderTest.someLibraryMethod2());
    }
    
    @Test public void testSomeLibraryMethod3() {
        assertEquals("someLibraryMethod3 should return 'MyTestString'", classUnderTest.someLibraryMethod3(), "MyTestString");
    }
}
